apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{projectName}}-gateway-https
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    #kubernetes.io/ingress.allow-http: "false"
    appgw.ingress.kubernetes.io/ssl-redirect: "{{k8s.ingress.ssl-redirect}}"
    # https://azure.github.io/application-gateway-kubernetes-ingress/annotations/
    appgw.ingress.kubernetes.io/use-private-ip: "false"
    appgw.ingress.kubernetes.io/health-probe-path: "/"
    appgw.ingress.kubernetes.io/cookie-based-affinity: "false"
    #appgw.ingress.kubernetes.io/cookie-based-affinity-distinct-name: "true"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: "{{k8s.ingress.certificate}}"
spec:
  rules:
  - host: "{{physician-portal.domain-name}}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{projectName}}
            port: 
              number: 80
